### ISSUE TITLE
关于音乐名可能导致无法下载的问题

### ISSUE THREAD

**Issue by pokoblin** [yanunon/NeteaseCloudMusic#1]
比如[这首歌](http://music.163.com/#/song?id=16148113)就会有下载不了的情况，猜测会不会是歌名里的？号导致的？

**Comment by yanunon** [comment]
@bindiry 我表示可以正常下载啊，能贴一下是什么错误么？

**Comment by pokoblin** [comment]
我这点了没反应，而且我开启chrome的控制台也没显示任何错误，我发给另一个用此插件的朋友测试，他点了也没反应。

**Comment by yanunon** [comment]
@bindiry 原来你说的是chrome插件。的确是因为歌名里面的问号不符要求，现已改好并发布更新，可能1个小时左右生效。

**Comment by pokoblin** [comment]
哈，已看到更新，感谢提供这么好用的插件。
